### ISSUE TITLE
Setting scope with Laravel config not working

### ISSUE THREAD

**Issue by grayxr** [Andreyco/Instagram-for-PHP#1]
I was tinkering with Client.php and it seems that the 'mergeScope' method is not working properly with the Laravel implementation. I try to set the scope array, but I keep getting the default 'basic' as the scope parameter when trying to authorize a user with  the 'getLoginUrl' method.

**Comment by Andreyco** [comment]
Will take a look into this.

**Comment by Andreyco** [comment]
`getLoginUrl` method takes array of scopes. If this array is empty, defaul `basic` scope is set instead.
Actualy any other scope is merged with this default scope. Everytime.  

@jgrayillustrate could you post some example code and expectation?
Thanks

**Comment by grayxr** [comment]
You can view the relevant code in my git repo, [here](https://github.com/jgrayillustrate/microlens_settings/blob/master/app/config/packages/andreyco/instagram/config.php) and [here](https://github.com/jgrayillustrate/microlens_settings/blob/master/app/views/partials/welcome.blade.php). For right now I'm pulling in a forked repo to fix the issue temporarily. BTW, I changed the scopes array back to using only 'basic'. I tried using 'likes' to no avail without using my forked version.

**Comment by Andreyco** [comment]
Fixed.
