### ISSUE TITLE
Deprecated.

### ISSUE THREAD

**Issue by zerolfc** [Andreyco/Instagram-for-PHP#11]
`getUserFeed` = `users/self/feed`  deprecated
`getPopularMedia` = `media/popular` deprecated
`getUserFollower` =  `/users/USER-ID/follows` use new endpoint `/users/self/follows`
`getUserFollows` = `/users/USER-ID/followed-by` use new endpoint `/users/self/followed-by`

``` php
// Use access_token instead
public function getUserMedia($id = 'self', $limit = 20) {
 return $this->_makeCall('users/' . $id . '/media/recent', true, array('count' => $limit));
}
```

https://www.instagram.com/developer/changelog/

**Comment by Andreyco** [comment]
Hi there,
willing to create PR?
