### ISSUE TITLE
The access_token provided is invalid

### ISSUE THREAD

**Issue by albertofdb** [Andreyco/Instagram-for-PHP#15]
`object(stdClass)#29 (1) { ["meta"]=> object(stdClass)#36 (3) { ["code"]=> int(400) ["error_type"]=> string(25) "OAuthAccessTokenException" ["error_message"]=> string(37) "The access_token provided is invalid." } }`

This error appears when I use the function below:

```
public function searchUser($name, $limit = 20) {
      return $this->_makeCall('users/search', false, array('q' => $name, 'count' => $limit));
 }
```

I have had to modify the second argument to `true` to solve it.

**Comment by vanam** [comment]
+1

**Comment by patrickdundas** [comment]
I also had this issue. The pull request @vanam submitted fixes this issue, hopefully it'll be approved soon, as the repository as it is now is unusable. I'd recommend downloading Client.php from his pull request to patch your pages, even though it hasn't been approved yet. Thanks @vanam! You saved me a lot of work and trouble.

**Comment by Andreyco** [comment]
PR accepted. Please, check out v4, since it contains breaking changes
