### ISSUE TITLE
Is this going to be updated for the new API?

### ISSUE THREAD

**Issue by nathanaelphilip** [Andreyco/Instagram-for-PHP#8]

**Comment by Andreyco** [comment]
Please, specify what changes are priority for you.

**Comment by nathanaelphilip** [comment]
Sorry, I kind of freaked out because a lot of things were broken. Apparently you have to invite users to your Client’s Sandbox if you want to be able to pull data from their accounts.

**Comment by Andreyco** [comment]
Yes, you either invite them or have limited (in some situations) access to their data.
