### ISSUE TITLE
Example with Sandbox mode

### ISSUE THREAD

**Issue by nathanaelphilip** [Andreyco/Instagram-for-PHP#9]
Has anyone had success pulling in a user’s media in Sandbox mode?

**Comment by Andreyco** [comment]
yep, first 20 media only... Will try to setup example asap

**Comment by nathanaelphilip** [comment]
I just keep getting an authorization error. I’ve added the user to my sandbox and also created a client on their account, but neither work.

**Comment by richardvanbergen** [comment]
Having the same problem right now. Is this related to their platform update?

**Comment by Andreyco** [comment]
@nathanaelphilip 
are you able to provide additional feedback on this. I've just created sandbox app, authenticated and received access token with user profile. All without problems.

@enrichit 
yes, this is part of recent changes. Brief list of change http://developers.instagram.com/post/133424514006/instagram-platform-update
More can be found across docs pages.

**Comment by Andreyco** [comment]
@nathanaelphilip I think you might have used `getUserMedia` with it's default `limit = 0`, which could potentially lead to empty sets. I have modified code to query 20 records by default (on all endpoints) and from now on exception is thrown when you are trying to query less than 1 record (which does not make sense)
See changes for v3.4.0
